spring:
  profiles:
    active: default
  datasource:
    name: Delivery20Pool
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

  jpa:
    database: default
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  http:
    converters:
      preferred-json-mapper: gson
server:
  port: 8081

logging:
  level:
    root: INFO
    com:
      cafeto: DEBUG
    org:
      springframework:
        web: INFO
      hibernate: INFO

